spring:
  server:
    port: 8080
  banner:
      location: /static/banner.txt
  datasource:
    url: jdbc:mysql://localhost:3306/EduBox
    username: root
    password: Varshini@29
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update   # use "create" for fresh start
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect