server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sso_db
    username: root
    password: Santosh@22124
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update   # use "create" for fresh start
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
